rabbitmq:
  container_name: dev_rabbitmq
  image: rabbitmq:3.5.6-management
  hostname: rabbitmq
  ports:
   - "5672:5672"
   - "15672:15672"
  volumes:
    - /mnt/sda1/data/rabbitmq:/var/lib/rabbitmq

redis:
  container_name: dev_redis
  image: redis:2.8.19
  command: redis-server --appendonly yes
  ports:
    - "6379:6379"
  volumes:
    - /mnt/sda1/data/redis:/data

postgres:
  container_name: dev_postgres
  image: postgres:9.4.2
  ports:
    - "5432:5432"
  volumes:
    - /mnt/sda1/data/postgresql:/var/lib/postgresql/data

mongo:
  container_name: dev_mongo
  image: mongo:2.4.14
  ports:
    - "27017:27017"
  volumes:
    - /mnt/sda1/data/mongo:/data
